version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation create-stack \
              --template-file network.yml \
              --parameters network-parameters.json \
              --stack-name my-stack \
              --region=eu-west-1
workflows:
  my_workflow:
    jobs:
      - create_infrastructure